//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instrument()
        {
            this.StockPrices = new HashSet<StockPrice>();
            this.Trades = new HashSet<Trade>();
        }
    
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string Exchange { get; set; }
        public string Underlying { get; set; }
        public Nullable<double> Strike { get; set; }
        public Nullable<double> Tenor { get; set; }
        public Nullable<bool> IsCall { get; set; }
        public int TypeID { get; set; }
        public Nullable<double> Rebate { get; set; }
        public Nullable<double> Barrier { get; set; }
        public string BarrierType { get; set; }
        public string Ticker { get; set; }
    
        public virtual InstType InstType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockPrice> StockPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trade> Trades { get; set; }
    }
}
